# Sponsor links will be displayed on your repo page
# See: https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository

github: [tunsuy]
# ko_fi: your_kofi_username
# patreon: your_patreon_username
# open_collective: synapse
# custom: ["https://www.buymeacoffee.com/yourusername"]
